apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hofb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0049-tenant/tkrw-pr714-0075-0049-app/devfile-sample-hofb@sha256:99666e8b4bfb271d4a6173f5f9f0177cf205da151abdbda2ede98bd59163707f
        name: my-nodejs
        resources: {}
status: {}
